# Mid EXAM : Tools and Techniques Data Science 

# Task 1: ( 5 Marks)  Warp up 

# Note : Rename the file with your name and id and also mention your name and id inside here 

In [1]:
# Q1. Here, we take each element in the list a (temporarily assigning it the value i) 
a = [5, 10, 15, 20]

In [ ]:
# (i)	Find the square each element in the list. This creates a new list called b and does not modify a through data comprehension.

In [3]:
a= [5,10,15,20]
b= [i**2 for i in a]
print(b)

[25, 100, 225, 400]


In [19]:
# (ii)	Write a conditional statement of only squaring the elements if the element is not equal to 10.



In [4]:
a= [5,10,15,20]
b= [i ** 2 for i in a if i != 10]
print(b) 

[25, 225, 400]


In [5]:
# Q2. (i) Write the command of random samples from a uniform distribution between 0 and 1? 

In [6]:
import numpy as np 

In [7]:
import random
samples = [random.uniform(0, 1) for _ in range(10)]
print(samples)

[0.08869305358969426, 0.6660448961066388, 0.6199065648512352, 0.12785509855773503, 0.8514545001948345, 0.9397945523732018, 0.24417510584415947, 0.9710191168778399, 0.6935326213937232, 0.5252629569018674]


In [8]:
#(ii)	Write the command to slice the column 1? 

In [10]:
matrix [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
       ]
column_1 = [row[1] for row in matrix]

print(column_1)


NameError: name 'matrix' is not defined

In [11]:
#(iii)	Write the command of first and third elements in column 1?

In [12]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

column_1 = [row[1] for row in matrix]

first_element = column_1[0]
third_element = column_1[2]

print(first_element, third_element)

2 8


In [13]:
#(iv)	 Write the command of returns an 8 x 4 array

In [14]:
import numpy as np

array = np.zeros((8, 4))

print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
import pandas as pd 

In [16]:
#Q3. Create a Series that looks like this below:
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

SyntaxError: invalid syntax (4174055471.py, line 2)

In [18]:
import pandas as pd

data = [4, 1, 2, 1]

series = pd.Series(data)

print(series)

0    4
1    1
2    2
3    1
dtype: int64


In [25]:
# Q  4 Create the Data frame  as th output[27]

In [19]:
data = pd.DataFrame({'Apples':[35,41], 'Bananas':[21,34]}, index=['2017Sales','2018Sales'])
data

Apples  Bananas
2017Sales      35       21
2018Sales      41       34

In [ ]:
#Q4. create Dataframe then find imputation for these missing NaN in the out[47]

In [20]:
import pandas as pd
import numpy as np

# Creating a DataFrame
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [6, np.nan, 8, np.nan, 10],
    'C': [11, 12, 13, np.nan, 15]
}

df = pd.DataFrame(data)

# Imputation for missing values
df_imputed = df.fillna(df.mean())

print(df_imputed)

     A     B      C
0  1.0   6.0  11.00
1  2.0   8.0  12.00
2  3.0   8.0  13.00
3  4.0   8.0  12.75
4  5.0  10.0  15.00


In [27]:
df

Apples  Bananas
2017Sales      35       21
2018Sales      41       34

In [21]:
data = ({'Age':[23, 39, 45, np.nan], 'Gender':['M','F','F','M'],'Income':[24200,np.nan,45390,np.nan], 'Religion':['Muslim','chirstian',np.nan,'Muslim']})
df = pd.DataFrame(data)
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [47]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [39]:
#Q4(i)	

In [29]:
#(ii)	Compute the appropriate missing values in religion attribute? 

In [28]:
df['religion'].fillna(df['religion'].mode()[0],inplace=false)
df

KeyError: 'religion'

In [22]:
#(iii)	Drop the columns where any of the elements is nan

In [23]:
result = df.dropna(axis=0)
result

Age Gender   Income Religion
0  23.0      M  24200.0   Muslim

In [24]:
#(iv)	Keep only the rows with at least 2 non-na values

In [26]:
result = df.dropna(thresh=1)
print(result)

    Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim
